# Plugins
Plugins: [jekyll-sitemap, jekyll-paginate-v2] 
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Yo Aislado"
email: "paolakatherine.ar@gmail.com"
description: "Plataforma para agrupar pequeños negocios en Mendoza."
baseurl: "/"
url: "http://pkpacheco.github.io/yoaislado/"
permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "mailto:masconmdz@gmail.com"

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/restaurantes/", text: "Restaurantes"}
 - {permalink: "/servicios/", text: "Servicios"}
 - {permalink: "/donaciones/", text: "Donaciones"}


# Hero Block
heroImage: "grey.png"
heroTitle: "Restaurantes, Donaciones y Servicios"
eventDate: "Mendoza"
# typeoutTextValues: '"", "Restaurantes", "Negocios ", "Donaciones ", "Servicios" ,"otros"'
# typeoutFallback: "Restaurantes, Donaciones y Servicios"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdWixfbqX1agPO_XFXZCrvJtq5HT62dCZHyDmb4Fei7e8q1ng/viewform", text: "Compartir restaurantes | comida "}
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLScUaohsNWJvqvhO_fpl0tgcsRDiWMQRti9zOOXB6ps3d1dnSQ/viewform", text: "Compartir un lugar que recibe donaciones"}
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdOq32lk6XLzSU-LJUg7pRVbeZaa32luiy4JGwvEPgFPU3Bcg/viewform", text: "Compartir un negocio de servicios"}

# About Block
aboutTitle: "Conocé Yo Aislado"
aboutBlock:
 - {title: "Restaurantes", image: "food.png", link: "restaurantes", text: "Restaurantes y Servicios de Comida." }
 - {title: "Servicios ", image: "services.png", link: "servicios", text: "Servicios en General." }
 - {title: "Donaciones", image: "donacion.jpg", link: "donaciones", text: "Donaciones." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "Locales", detail: ""}
 - {count: "10", specialCharacter: "+", info: "Restaurantes", detail: "y pequeños negocios"}
 - {count: "10", specialCharacter: "+", info: "Servicios", detail: "en tu casa"}
 - {count: "10", specialCharacter: "", info: "Locales", detail: "para donar y ayudar"}


# Footer
socialLinks:
 - {link: "https://www.facebook.com/Yo-Aislado-104862687863958", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://github.com/PKpacheco/yoaislado", text: "GitHub"}

 -
  title: "Creador y Mantenedor"
  links:

   - {link: "mailto:paolakatherine.ar@gmail.com", text: "paolakatherine.ar@gmail.com"}
