# Plugins
Plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Yo Aislado"
email: "paolakatherine.ar@gmail.com"
description: "Plataforma para agrupar pequeños negocios en Mendoza."
baseurl: "/"
url: "http://pkpacheco.github.io/yoaislado/"
permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "mailto:masconmdz@gmail.com"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/restaurantes/", text: "Restaurantes"}
 - {permalink: "/services/", text: "Servicios"}
 - {permalink: "/donations/", text: "Donacion"}


# Hero Block
heroImage: "fundo_escuro.png"
heroTitle: "Yo Aislado | <typeout> "
eventDate: "Mendoza"
typeoutTextValues: '"", "Restaurantes", "Negocios ", "Donaciones ", "Servicios" ,"otros"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdWixfbqX1agPO_XFXZCrvJtq5HT62dCZHyDmb4Fei7e8q1ng/viewform", text: "Quiero ayudar compartiendo un negocio de Comida"}
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdWixfbqX1agPO_XFXZCrvJtq5HT62dCZHyDmb4Fei7e8q1ng/viewform", text: "Quiero ayudar compartiendo un lugar que recibe donaciones"}
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdWixfbqX1agPO_XFXZCrvJtq5HT62dCZHyDmb4Fei7e8q1ng/viewform", text: "Quiero ayudar compartiendo un negocio de servicio"}

# About Block
aboutTitle: "Conocé Yo Aislado"
aboutBlock:
 - {title: "Restaurantes", image: "food.png", text: "Restaurantes y Servicios de Comida." }
 - {title: "Servicios ", image: "services.png", text: "Servicios en General." }
 - {title: "Donaciones", image: "donacion.jpg", text: "Donaciones." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "Locales", detail: ""}
 - {count: "10", specialCharacter: "+", info: "Restaurantes", detail: "y pequeños negocios"}
 - {count: "10", specialCharacter: "+", info: "Servicios", detail: "en tu casa"}
 - {count: "10", specialCharacter: "", info: "Locales", detail: "para donar y ayudar"}

# Restaurant Block
rockstarSpeakersImage: "restaurante.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Restaurantes | Comida"
rockstarSpeakersButtonText: "Ver todos los Restaurantes"

# Footer
socialLinks:
 - {link: "https://www.facebook.com/Yo-Aislado-104862687863958", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://github.com/PKpacheco/yoaislado", text: "GitHub"}

 -
  title: "Creador y Mantenedor"
  links:

   - {link: "mailto:paolakatherine.ar@gmail.com", text: "paolakatherine.ar@gmail.com"}
