# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Yo Aislado"
email: "paolakatherine.ar@gmail.com"
description: "Plataforma para agrupar pequeños negocios en Mendoza."
baseurl: "/"
url: "http://pkpacheco.github.io/yoaislado/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-163890575-1"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/restaurantes/", text: "Restaurantes"}
 - {permalink: "/servicios/", text: "Servicios"}
 - {permalink: "/donaciones/", text: "Donaciones"}


# Hero Block
heroImage: "grey.png"
heroTitle: "Restaurantes, Donaciones y Servicios"
eventDate: "Mendoza"
# typeoutTextValues: '"", "Restaurantes", "Negocios ", "Donaciones ", "Servicios" ,"otros"'
# typeoutFallback: "Restaurantes, Donaciones y Servicios"
heroButtons:
 - {link: "https://forms.gle/FkJCYyHxX4x5mUiL7", text: "Quiero colaborar "}

# About Block
aboutTitle: "Conocé Yo Aislado"
aboutBlock:
 - {title: "Restaurantes", image: "food.png", link: "restaurantes", text: "Restaurantes y Servicios de Comida." }
 - {title: "Servicios ", image: "services.png", link: "servicios", text: "Servicios en General." }
 - {title: "Donaciones", image: "donacion.jpg", link: "donaciones", text: "Donaciones." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "Locales", detail: ""}
 - {count: "10", specialCharacter: "+", info: "Restaurantes", detail: "y pequeños negocios"}
 - {count: "10", specialCharacter: "+", info: "Servicios", detail: "en tu casa"}
 - {count: "10", specialCharacter: "", info: "Locales", detail: "para donar y ayudar"}


# Footer
socialLinks:
 - {link: "https://www.facebook.com/Yo-Aislado-104862687863958", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://github.com/PKpacheco/yoaislado", text: "GitHub"}

 -
  title: "Creador y Mantenedor"
  links:

   - {link: "mailto:paolakatherine.ar@gmail.com", text: "paolakatherine.ar@gmail.com"}
