
 -
   id: 1
   name: "Don"
   surname: "Mario"
   company: "Restaurante"
   title: "Servicios de envio a domicicio, pedidos por el sitio"
   bio: "Envios a la Casa"
   thumbnailUrl: donmario.png
   rockstar: true
   ribbon:
     - {abbr: "Envios", title: "Envios", url: "http://donmario.com.ar/carta-para-envio-a-domicilio/"}
     - {name: "sitio", link: "http://donmario.com.ar/carta-para-envio-a-domicilio/"}

 -
    id: 2
    name: "Sentite"
    surname: "Listo"
    company: "Comida Congelada"
    title: "Envio de comida congelada a domicicio"
    bio: "Viandas semanales que llegan a tu casa "
    thumbnailUrl: sentitelisto.png
    rockstar: true
    ribbon:
      - {abbr: "Viandas", title: "Viandas"}
      - {abbr: "Instagram", title: "Instagram", url: "https://www.instagram.com/sentitelisto/"}
