
-
  id: 1
  name: "Tintureria"
  surname: "ABC"
  company: ""
  title: "Servicios de retiro a domicicio, llamar por whatsapp"
  bio: "Retiramos su pedido en la casa. tel: 123 456 789"
  thumbnailUrl: laundry.jpg
  rockstar: true
  ribbon:
    - {abbr: "Retiro | Whatsapp", title: "Retiro | Whatsapp", url: "tel:123-456-7890"}

-
  id: 2
  name: "Farmacia Del"
  surname: "Centro"
  company: "Farmacia "
  title: "Envio de medicamentos  a domicicio"
  bio: ""
  thumbnailUrl: pharmacy.jpg
  rockstar: true
  ribbon:
    - {abbr: "Envios | Whatsapp", title: "Retiro | Whatsapp", url: "tel:123-456-7890"}
    - {abbr: "Envios | Sitio", title: "Retiro | Teléfono", url: "htpps://google.com"}

-
  id: 3
  name: "Mayorista en"
  surname: "Country"
  company: "Mercado "
  title: "Envio a domicicio"
  bio: ""
  thumbnailUrl: market.png
  rockstar: true
  ribbon:
    - {abbr: "Envios | Whatsapp", title: "Retiro | Whatsapp", url: "tel:123-456-7890"}
    - {abbr: "Envios | Sitio", title: "Retiro | Teléfono", url: "htpps://google.com"}

- 
  id: 4
  name: "Mercado "
  surname: "ABC"
  company: "Mercado "
  title: "Envio a domicicio"
  bio: ""
  thumbnailUrl: market2.jpg
  rockstar: true
  ribbon:
    - {abbr: "Envios | Whatsapp", title: "Retiro | Whatsapp", url: "tel:123-456-7890"}
    - {abbr: "Envios | Sitio", title: "Retiro | Teléfono", url: "htpps://google.com"}